# -*- coding: utf-8 -*-
DRY_RUN=False
TMP_PATH='/tmp/droid4_modem/'
USER_DATA_PREFIX='/root/user_data/droid4/'
PATH_PREFIX='/usr/local/share/droid4/python3_packages/modem/'
DEV='/dev/'
SMS_SEND_DEV=DEV+"gsmtty3"
MODEM_DEV=DEV+"gsmtty1"
INCOMING_SMS_FILENAME=DEV+'gsmtty9'
LOG_PATH_PREFIX=USER_DATA_PREFIX+'modem/logs/'
DATABASE_FILENAME=USER_DATA_PREFIX+'modem/dynamic_data/modem.db'
SERVER_ADDRESS=TMP_PATH+'server'
NOTIFICATION_FILENAME='/root/modem_notifications'
NOTIFY_EVENTS=True
INIT_MODEM=True
VIBRATOR_ENABLE=True
LEDS_ENABLE=True
#client
PHONE_LIST_FILENAME="/usr/local/share/droid4/emacs/phone_list.txt"
NICKNAME_LIST_FILENAME="/usr/local/share/droid4/emacs/nickname_hash.el"
